#!/bin/sh

cat /proc/cmdline | grep " tmp-rw-lpie" > /dev/null
if [ $? -eq 0 ] ; then
    echo "performing temporary rw boot"
    sed -i 's/ tmp-rw-lpie//g' /boot/cmdline.txt
    sed -i 's/$/ lpie/' /boot/cmdline.txt
fi

